aws_dbt_snoflake_project:
  outputs:
    dev:
      account: SOSTDNH-YP30025
      database: AIRBNB
      password: Priyadarsani9078@123
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 1
      type: snowflake
      user: PRIYADARSANIBISWAL633
      warehouse: COMPUTE_WH
  target: dev
